on:
  push:
  workflow_dispatch:

name: 🚀 Deploy Nukta Publish

jobs:
  deployment:
    name: 🎉 Deploy
    environment: NUKTA
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🔑 Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          cat <<EOF > ~/.ssh/id_ed25519
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 65002 82.198.227.109 >> ~/.ssh/known_hosts

      - name: 🐘 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: zip

      - name: 📂 Deploy theme to publish.nukta.co.tz
        run: php scripts/deploy.php
        env:
          HOME: /home/runner
